# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

def update_package_json(new_version)
	path = "../package.json"
    regex = /"version": ".*",/
    result_value = "\"version\": \"#{new_version}\","

    update_file(path, regex, result_value)
end

def update_aegis_url_in_tests(url)
	path = Dir['../**/__integrationTests__/constants.ts'].first

    regex = /AEGIS_URL = .*/
    value = "AEGIS_URL = \"#{url}\""

    update_file(path, regex, value)
end

def update_stripe_config_in_tests(product_id, subscription_id)
	path = Dir['../**/__integrationTests__/constants.ts'].first

    # Update STRIPE_PRODUCT_ID
    product_regex = /STRIPE_PRODUCT_ID = .*/
    product_value = "STRIPE_PRODUCT_ID = #{product_id}"
    update_file(path, product_regex, product_value)

    # Update STRIPE_SUBSCRIPTION_ID
    subscription_regex = /STRIPE_SUBSCRIPTION_ID = .*/
    subscription_value = "STRIPE_SUBSCRIPTION_ID = #{subscription_id}"
    update_file(path, subscription_regex, subscription_value)
end

def update_file(path, regex, result_value)
	file = File.read(path)
    new_content = file.gsub(regex, result_value)
    File.open(path, 'w') { |line| line.puts new_content }
end

platform :mac do
  lane :bump do |options|
  	new_version = options[:version]

	update_package_json(new_version)
  end

  lane :setAegisUrl do |options|
    path = options[:url]

	update_aegis_url_in_tests(path)
  end

  lane :updateStripeSecrets do |options|
    product_id = options[:product_id]
    subscription_id = options[:subscription_id]

	update_stripe_config_in_tests(product_id, subscription_id)
  end
end
