name: Planned integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    concurrency:
      group: web_integration_tests
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - name: Set Aegis url
        run: |
          fastlane setAegisUrl url:${{ secrets.AEGIS_URL }}

      - name: Set Stripe secrets
        run: |
          fastlane updateStripeSecrets product_id:${{ vars.STRIPE_PRODUCT_ID }} subscription_id:${{ vars.STRIPE_SUBSCRIPTION_ID }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn

      - name: Tests
        run: |
          yarn integrationTests
