name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    name: Upload archives
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build typescript
        run: |
          yarn
          yarn build

      - name: Setup node for publishing
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
